### ISSUE TITLE
プロダクト3Dモデルviewページ作成

### ISSUE THREAD

**Issue by TatsuyaUkai** [katayude/modelmemo#6]
レイアウトから、Three.jsを使った３Dモデル画面の表示まで。

**Comment by katayude** [comment]
がんばれー。まず、3Dモデルの保存はデータベース使わずにpublicに3Dmodelってフォルダ作って保存しようか

**Comment by TatsuyaUkai** [comment]
やりました！でも、表示させようとしたらエラーが出ました。困ってます。
![スクリーンショット (73)](https://github.com/katayude/modelmemo/assets/143098443/0a6db2fe-4882-43d9-8638-61857ea90376)

**Comment by TatsuyaUkai** [comment]
Server Component と Client Componentを区別しなくてはならなくて、そのためにuse clientを入れたのですが、うまくいきません。

**Comment by TatsuyaUkai** [comment]
![スクリーンショット (74)](https://github.com/katayude/modelmemo/assets/143098443/441a34a8-6512-47da-a535-a2e941a64a9a)

**Comment by katayude** [comment]
多分、return文の中でCSSのスタイルを記述しているからだと思う。const size ={}の部分ね。
returnの外でconst size ={}とか定義したらいいよ。Mainmenue.tsxとかに記述あるから参考にして！

**Comment by TatsuyaUkai** [comment]
use clientに”を付けたら治りました！ありがとうございます！

**Comment by TatsuyaUkai** [comment]
３Dモデル表示できた！あとはページの全体的な構造を作る！
